# Generated by Django 4.0.4 on 2022-05-16 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=255, verbose_name='news posted by')),
                ('username', models.CharField(max_length=1000)),
                ('news_id', models.IntegerField()),
                ('score', models.IntegerField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=1000)),
                ('text', models.TextField(null=True)),
                ('url', models.URLField(max_length=1000, null=True, verbose_name='URL')),
                ('type', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=255, verbose_name='news posted by')),
                ('username', models.CharField(max_length=1000)),
                ('text', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=1000)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_api.newsdb')),
            ],
        ),
    ]
